[package]
name = "u2f"
version = "0.1.0"
authors = ["Rob N ★ <robn@robn.io>"]
license = "MIT"
build = "build.rs"

[build-dependencies]
serde_codegen = "0.8"

[dependencies]
serde = "0.8"
serde_json = "0.8"
ring = "*"
webpki = "*"
untrusted = "*"
base64 = "*"
error-chain = "*"
hex-slice = "*"
